config/routes.rb
Rails.application.routes.draw do
  resources :reports
  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :markets do
    get 'get_listing'

    resources :listings do
      get 'send_email'
      get 'rehab'
    end
  end

  resources :messages do
    get 'receive_sms', on: :collection
  end

  resources :deals

  resources :agents do
    collection do
      get 'download'
    end
  end

  root 'deals#index'

  get 'receive_sms', to: 'messages#receive_sms'

  resources :home do
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :messageable, polymorphic: true
end

app/controllers/messages_controller.rb
class MessagesController < BaseController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:receive_sms]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.order('created_at DESC').paginate(:page => params[:page], :per_page => Setting.i(:default_per_page))
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        if @message.reply.present?
          ReplySmsService.call(@message)
          @message.update(status: 'replied')
        end
        format.html { redirect_to @message, notice: 'Message was successfully sent.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def receive_sms
    agent = Agent.find_by_phone(params[:From])
    message = Message.new(
      content: params[:Text],
      phone_number: params[:From],
      messageable: agent,
      status: 'new'
    )
    ForwardSmsService.new(agent, message).call if message.save and agent.present?

    render nothing: true
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:content, :reply, :messageable_id, :messageable_type, :phone_number, :status)
  end
end

app/views/messages/_form.html.haml
= form_for @message, html: { class: "form-horizontal", role: "form" } do |f|
  -if @message.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"

      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label 'Incoming', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :content, class: 'form-control'
  .form-group
    = f.label 'Outgoing', class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_area :reply, class: 'form-control'
  .form-group
    = f.label :phone_number, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :phone_number, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit 'Reply', class: 'btn btn-primary'

app/views/messages/edit.html.haml
.panel.panel-flat
  .panel-heading
    %h5.panel-title
      Reply message
  .panel-body
    .row
      = link_to messages_path, class: 'btn btn-primary pull-right back-btn' do
        %i.icon-circle-left2.position-left
        Back
      = link_to @message, class: 'btn btn-primary pull-right' do
        %span.glyphicon.glyphicon-info-sign
        Show
    = render 'form'

app/views/messages/index.html.haml
.panel.panel-flat
  .panel-heading
    %h5.panel-title
      Messages
  .panel-body
  #DataTables_Table_2_wrapper.dataTables_wrapper.no-footer
    .datatable-scroll
      %table#DataTables_Table_2.table.table-responsive.datatable-save-state.dataTable.no-footer{"aria-describedby" => "DataTables_Table_2_info", :role => "grid"}
        %thead
          %tr{:role => "row"}
            %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "First Name: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Incoming

            %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Last Name: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Outgoing
            %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Job Title: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Sender
            %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "DOB: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Phone number
            %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Status
            %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Created at
            %th.text-center.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "3", :rowspan => "1", :tabindex => "0"} Action
        %tbody
          - @messages.each do |message|
            %tr{ role: "row" }
              %td= message.content
              %td= message.reply
              - if message.messageable_id
                %td= link_to message.messageable.to_s, polymorphic_path(message.messageable)
              - else
                %td= 'N/A'
              %td= message.phone_number
              %td= message.status
              %td= message.created_at
              %td
                = link_to message, class: "text-primary-600" do
                  %i.icon-info22
                  Show
              %td
                = link_to edit_message_path(message), class: "text-success-600" do
                  %i.icon-reply
                  Reply
              %td
                = link_to message, data: { confirm: 'Are you sure?' }, method: :delete, class: "text-danger-600" do
                  %i.icon-trash
                  Delete

    .datatable-footer
      #DataTables_Table_2_info.dataTables_info{"aria-live" => "polite", :role => "status"}
      #DataTables_Table_2_paginate.dataTables_paginate.paging_simple_numbers
        = will_paginate @messages, renderer: BootstrapPagination::Rails

app/views/messages/new.html.haml
.page-header
  = link_to messages_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New message

= render 'form'

app/views/messages/show.html.haml
.panel.panel-flat
  .panel-heading
    %h5.panel-title Message Information

  .panel-body
    .row
      = link_to messages_path, class: 'btn btn-primary pull-right back-btn' do
        %i.icon-circle-left2.position-left
        Back
    .table-responsive.content-group
      %table.table.table-framed
        %thead
          %tr
            %th.col-xs-3 Message information

            %th Value
        %tbody
          %tr
            %td
              %span.text-semibold Content
            %td= @message.content
          %tr
            %td
              %span.text-semibold Reply
            %td= @message.reply
          %tr
            %td
              %span.text-semibold Sender
            %td
              - if @message.messageable_id
                = link_to @message.messageable.to_s, polymorphic_path(@message.messageable)
              - else
                N/A
          %tr
            %td
              %span.text-semibold Phone number
            %td= @message.phone_number
          %tr
            %td
              %span.text-semibold Status
            %td
              = @message.status