config/routes.rb
Rails.application.routes.draw do
  resources :reports
  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :markets do
    get 'get_listing'

    resources :listings do
      get 'send_email'
      get 'rehab'
    end
  end

  resources :messages do
    get 'receive_sms', on: :collection
  end

  resources :deals

  resources :agents do
    collection do
      get 'download'
    end
  end

  root 'deals#index'

  get 'receive_sms', to: 'messages#receive_sms'

  resources :home do
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :market
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show]

  respond_to :html

  def index
    @market = Market.find(params[:market_id])

    @show_hotdeals_option = false
    if show_hotdeal_params.present?
      @show_hotdeals_option = show_hotdeal_params == "true"
      @listings = Listing.where(hot_deal: @show_hotdeals_option, market: @market).order('added_date DESC').paginate(:page => params[:page], :per_page => Setting.i(:default_per_page))
    else
      @listings = Listing.where(market: @market).order('added_date DESC').paginate(:page => params[:page], :per_page => Setting.i(:default_per_page))
    end

    respond_with(@listings)
  end

  def show
    respond_with(@listing)
  end

  def edit
  end

  def send_email
    listing = Listing.find(params[:listing_id])
    OfferMailer.notify_customer(listing).deliver_later

    flash[:notice] = "Sent email successfully."
    redirect_to market_listings_path(listing.market)
  end

  def rehab
    listing = Listing.find(params[:listing_id])

    begin
      AutoOrderBidsForRehab.new(listing).call
      flash[:notice] = "Rehab successfully."
    rescue
      flash[:notice] = "Rehad fail. Please try again!"
    end

    redirect_to market_listings_path(listing.market)
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def show_hotdeal_params
    params[:hot_deal_only]
  end
end

app/views/listings/_listings_content.html.haml
#DataTables_Table_2_wrapper.dataTables_wrapper.no-footer
  .datatable-scroll
    %table#DataTables_Table_2.table.table-responsive.datatable-save-state.dataTable.no-footer{"aria-describedby" => "DataTables_Table_2_info", :role => "grid"}
      %thead
        %tr{:role => "row"}
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "First Name: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Hot Deal
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Last Name: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Price
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Job Title: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Comps
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "DOB: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Zestimate
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} ARV
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} %ARV
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Rent
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Address
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} City
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Bed
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Bath
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Sq Ft
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Added Date
          %th.text-center.sorting_disabled{"aria-label" => "Actions", :colspan => "2", :rowspan => "1", :style => "width: 100px;"} Action
      %tbody
        - @listings.each do |listing|
          %tr{ role: "row" }
            - if listing.hot_deal
              %td
                %span.label.label-danger= "Hot Deal"
            - else
              %td
                %span

            %td= format_currency(listing.price)
            %td= format_currency(listing.comp)
            %td= format_currency(listing.zestimate)
            %td= format_currency(listing.arv.to_f)
            %td= number_to_percentage((listing.arv_percentage.to_f * 100), precision: 0)
            %td= format_currency(listing.rent.to_f)
            %td= listing.address
            %td= listing.city
            %td= listing.bed_rooms
            %td= listing.bath_rooms
            %td= listing.sq_ft
            %td= listing.added_date.utc.strftime("%m/%d/%Y")
            %td
              = link_to market_listing_send_email_path(@market, listing), class: "text-primary-600" do
                %i.icon-envelop
                Email
            %td
              = link_to market_listing_rehab_path(@market, listing), class: "text-primary-600" do
                %i.icon-circle
                Rehab

      / Scrollable datatable
  .datatable-footer
    #DataTables_Table_2_info.dataTables_info{"aria-live" => "polite", :role => "status"}
    #DataTables_Table_2_paginate.dataTables_paginate.paging_simple_numbers
      = will_paginate @listings, renderer: BootstrapPagination::Rails

app/views/listings/index.html.haml
.panel.panel-flat
  .panel-heading
    %h5.panel-title
      Deals
  .panel-body
    = form_tag market_listings_path(@market), method: "get", id: "search" do
      = check_box_tag 'hot_deal_only', 'true', @show_hotdeals_option, :onclick => "javascript: document.getElementById('search').submit();"
      %label Show only hot deals
  %div#dealsContent
    = render "listings_content"