config/routes.rb
Rails.application.routes.draw do
  resources :reports
  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :markets do
    get 'get_listing'

    resources :listings do
      get 'send_email'
      get 'rehab'
    end
  end

  resources :messages do
    get 'receive_sms', on: :collection
  end

  resources :deals

  resources :agents do
    collection do
      get 'download'
    end
  end

  root 'deals#index'

  get 'receive_sms', to: 'messages#receive_sms'

  resources :home do
  end

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :agent

  validates :price, :zestimate, :address, :city, :zipcode, :agent_id, presence: true
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @show_hotdeals_option = false
    if show_hotdeal_params.present?
      @show_hotdeals_option = show_hotdeal_params == "true"
      @deals = Deal.where(hot_deal: @show_hotdeals_option).order('created_at DESC').includes(:agent).paginate(:page => params[:page], :per_page => Setting.i(:default_per_page))
    else
      @deals = Deal.order('created_at DESC').includes(:agent).paginate(:page => params[:page], :per_page => Setting.i(:default_per_page))
    end

    respond_with(@deals)
  end

  def show
    respond_with(@deal)
  end

  def new
    @deal = Deal.new
    @agents = Agent.all
    respond_with(@deal)
  end

  def edit
    @agents = Agent.all
  end

  def create
    @deal = Deal.new(deal_params)
    @deal.save
    @agents = Agent.all
    respond_with(@deal)
  end

  def update
    @deal.update(deal_params)
    @agents = Agent.all
    respond_with(@deal)
  end

  def destroy
    @deal.destroy
    respond_with(@deal)
  end

  private

  def set_deal
    @deal = Deal.find(params[:id])
  end

  def deal_params
    params.require(:deal).permit(:listing_id, :price, :address, :city, :zipcode, :agent_id)
  end

  def show_hotdeal_params
    params[:hot_deal_only]
  end
end

app/views/deals/_deals_content.html.haml
#DataTables_Table_2_wrapper.dataTables_wrapper.no-footer
  .datatable-scroll
    %table#DataTables_Table_2.table.table-responsive.datatable-save-state.dataTable.no-footer{"aria-describedby" => "DataTables_Table_2_info", :role => "grid"}
      %thead
        %tr{:role => "row"}
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "First Name: activate to sort column descending", "aria-sort" => "ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Hot Deal
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Last Name: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Price
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Job Title: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Comps
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "DOB: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Zestimate
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Adress
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} City
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Bed
          %th.sorting_disabled{"aria-controls" => "DataTables_Table_2", "aria-label" => "Status: activate to sort column ascending", :colspan => "1", :rowspan => "1", :tabindex => "0"} Bath
          %th.text-center.sorting_disabled{"aria-label" => "Actions", :colspan => "1", :rowspan => "1", :style => "width: 100px;"} Action
      %tbody
        - @deals.each do |deal|
          %tr{ role: "row" }
            - if deal.hot_deal
              %td
                %span.label.label-danger= "Hot Deal"
            - else
              %td
                %span

            %td= format_currency(deal.price)
            %td= format_currency(deal.comp)
            %td= format_currency(deal.zestimate)
            %td= deal.address
            %td= deal.city
            %td= deal.bedroom
            %td= deal.bathroom
            %td
              = link_to deal, class: "text-primary-600" do
                %i.icon-info22
                Show


      / Scrollable datatable
  .datatable-footer
    #DataTables_Table_2_info.dataTables_info{"aria-live" => "polite", :role => "status"}
    #DataTables_Table_2_paginate.dataTables_paginate.paging_simple_numbers
      = will_paginate @deals, renderer: BootstrapPagination::Rails

app/views/deals/_form.html.haml
= form_for @deal, html: { class: "form-horizontal", role: "form" } do |f|
  -if @deal.errors.any?
    .alert.alert-danger.alert-dismissable{role: "alert"}
      %button.close{type: "button", data: {dismiss: "alert"} }
        %span{aria: {hidden: "true"} } &times;
        %span.sr-only Close
      %h4= "#{pluralize(@deal.errors.count, "error")} prohibited this deal from being saved:"

      %ul
        - @deal.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :listing_id, class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :listing_id, class: 'form-control'
  .form-group
    = f.label :price, class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :price, class: 'form-control'
  .form-group
    = f.label :address, class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :city, class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :zipcode, class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :zipcode, class: 'form-control'
  .form-group
    = f.label :agent, class: 'col-sm-2 control-label'
    .col-sm-4
      = f.select(:agent, options_for_select(@agents.pluck(:id), (@deal.agent.present? ? @deal.agent.id : nil)), {}, {class: 'form-control'})
  .form-group
    .col-sm-offset-2.col-sm-4
      = f.submit class: 'btn btn-primary'

app/views/deals/deals_content.js.erb
$("#dealsContent").html("<%= escape_javascript(render("deals_content")) %>");

app/views/deals/edit.html.haml
.page-header
  = link_to deals_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @deal, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing deal

= render 'form'

app/views/deals/index.html.haml
.panel.panel-flat
  .panel-heading
    %h5.panel-title
      Deals
  .panel-body
    = form_tag deals_path, method: "get", id: "search" do
      = check_box_tag 'hot_deal_only', 'true', @show_hotdeals_option, :onclick => "javascript: document.getElementById('search').submit();"
      %label Show only hot deals
  %div#dealsContent
    = render "deals_content"

app/views/deals/new.html.haml
.page-header
  = link_to deals_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New deal

= render 'form'

app/views/deals/show.html.haml
.panel.panel-flat
  .panel-heading
    %h5.panel-title Deal Information

  .panel-body
    .row
      = link_to deals_path, class: 'btn btn-primary pull-right back-btn' do
        %i.icon-circle-left2.position-left
        Back
    .table-responsive.content-group
      %table.table.table-framed
        %thead
          %tr
            %th.col-xs-3 Deal information

            %th Value
        %tbody
          - @deal.attributes.each do |attr_name, attr_value|
            %tr
              - if attr_name == "agent_id"
                %td
                  %span.text-semibold= "Agent"
                %td
                  = link_to @deal.agent.full_name, agent_path(@deal.agent)
              - else
                %td
                  %span.text-semibold= attr_name.humanize
                %td= attr_value