config/routes.rb
Rails.application.routes.draw do
  resources :reports
  devise_for :users
  scope "/admin" do
    resources :users
  end

  resources :markets do
    get 'get_listing'

    resources :listings do
      get 'send_email'
      get 'rehab'
    end
  end

  resources :messages do
    get 'receive_sms', on: :collection
  end

  resources :deals

  resources :agents do
    collection do
      get 'download'
    end
  end

  root 'deals#index'

  get 'receive_sms', to: 'messages#receive_sms'

  resources :home do
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title Deal Hunter

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.pace-done
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "DEAL HUNTER", root_path, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          %div
            %ul.nav.navbar-nav.pull-right
              %li.dropdown
                - if current_user.present?
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    #{current_user.email}
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to edit_user_registration_path do
                        %i.icon-cog
                        Profile
                    - if current_user.admin?
                      %li
                        = link_to new_user_path do
                          %i.icon-user
                          Create new user
                      %li
                        = link_to new_market_path do
                          %i.icon-plus3
                          Create new market
                    %li.divider
                    - if current_user && current_user.admin?
                      %li
                        = link_to users_path do
                          %i.icon-user-plus
                          Users Management
                      %li
                        = link_to markets_path do
                          %i.icon-gallery
                          Markets Management
                      %li.divider
                    %li
                      = link_to destroy_user_session_path, method: :delete do
                        %i.icon-switch2
                        Logout
                - else
                  %ul.nav.navbar-nav
                    %li
                      = link_to "Log in", new_user_session_path
          %div
            %ul.nav.navbar-nav
              - @markets_top.each do |market|
                %li{:class => active_class(market_listings_path(market))}
                  = link_to market.name, market_listings_path(market)
    .page-container{style: "margin-top: 40px"}
      .page-content
        .content-wrapper
          / Page header
          .page-header
            .page-header-content
              - flash.each do |name, msg|
                = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
                  %button.close{type: "button", data: {dismiss: "alert"} }
                    %span{aria: {hidden: "true"} } &times;
                    %span.sr-only Close
                  = msg

          / /page header
          / Content area
          .content
            = yield
            / Footer
            .footer.text-muted
              © 2016.
              = link_to "Deal Hunter", root_path
              by
              %a{:href => "http://www.mortgageclub.co", :target => "_blank"} MortgageClub